using Eto.Drawing;
using Eto.Forms;

namespace XtremeWorlds.Client.Tools
{
    public partial class frmAdminPanel : ToolForm
    {

        public readonly GroupBox fralvl2;
        public readonly Button cmdSetSprite;
        public readonly Button cmdSignEdit;
        public readonly Button cmdLOC;
        public readonly Button cmdBan;
        public readonly Button cmdMapreport;
        public readonly Button cmdRespawn;
        public readonly Button cmdPlayerSprite;
        public readonly Button cmdMapeditor;
        public readonly Button cmdWarpto;
        public readonly Button cmdSetJail;
        public readonly GroupBox fralvl1;
        public readonly Button cmdKick;
        public readonly Button cmdJail;
        public readonly Button cmdUnjail;
        public readonly Button cmdMute;
        public readonly Button cmdUnmute;
        public readonly GroupBox fralvl3;
        public readonly Button cmdNpcEditor;
        public readonly Button cmdItemEditor;
        public readonly Button cmdShopEditor;
        public readonly Button cmdSpellEditor;
        public readonly Button cmdDelbanlist;
        public readonly Button cmdKill;
        public readonly Button cmbArrowEditor;
        public readonly Button cmbClassEditor;
        public readonly Button cmdQuestEditor;
        public readonly Button cmdBookEditor;
        public readonly Button cmdEmoticonEditor;
        public readonly GroupBox fralvl4;
        public readonly Label AccessLevel;
        public readonly TextBox txtAccessLevel;
        public readonly Button cmdSetAccess;
        public readonly GroupBox fraSpriteNum;
        public readonly TextBox txtSpriteNum;
        public readonly GroupBox fraPlayer;
        public readonly TextBox txtPlayerName;
        public readonly GroupBox fraMapNum;
        public readonly TextBox txtMapNum;

        public frmAdminPanel() : base("admin")
        {
            Title = "Admin Panel";
            ClientSize = new Size(240, 457);
            Resizable = false;
            var root = new PixelLayout();
            Content = root;
            fralvl2 = new GroupBox();
            fralvl2.Size = new Size(97, 185);
            fralvl2.Text = "Mappers";
            RegisterControl("fralvl2", fralvl2);
            root.Add(fralvl2, 8, 267);
            var fralvl2Layout = new PixelLayout();
            fralvl2.Content = fralvl2Layout;
            cmdSetSprite = new Button();
            cmdSetSprite.Size = new Size(81, 17);
            cmdSetSprite.Text = "Set Sprite";
            cmdSetSprite.ToolTip = "Change your sprite";
            RegisterControl("cmdSetSprite", cmdSetSprite);
            fralvl2Layout.Add(cmdSetSprite, 8, 128);
            cmdSignEdit = new Button();
            cmdSignEdit.Size = new Size(81, 17);
            cmdSignEdit.Text = "Sign Editor";
            cmdSignEdit.ToolTip = "Ban a player";
            RegisterControl("cmdSignEdit", cmdSignEdit);
            fralvl2Layout.Add(cmdSignEdit, 8, 32);
            cmdLOC = new Button();
            cmdLOC.Size = new Size(81, 17);
            cmdLOC.Text = "Location";
            cmdLOC.ToolTip = "Find your location";
            RegisterControl("cmdLOC", cmdLOC);
            fralvl2Layout.Add(cmdLOC, 8, 112);
            cmdBan = new Button();
            cmdBan.Size = new Size(81, 17);
            cmdBan.Text = "Ban";
            cmdBan.ToolTip = "Ban a player";
            RegisterControl("cmdBan", cmdBan);
            fralvl2Layout.Add(cmdBan, 8, 96);
            cmdMapreport = new Button();
            cmdMapreport.Size = new Size(81, 17);
            cmdMapreport.Text = "Map Report";
            cmdMapreport.ToolTip = "View all free maps";
            RegisterControl("cmdMapreport", cmdMapreport);
            fralvl2Layout.Add(cmdMapreport, 8, 80);
            cmdRespawn = new Button();
            cmdRespawn.Size = new Size(81, 17);
            cmdRespawn.Text = "Respawn";
            cmdRespawn.ToolTip = "Respawn the map";
            RegisterControl("cmdRespawn", cmdRespawn);
            fralvl2Layout.Add(cmdRespawn, 8, 64);
            cmdPlayerSprite = new Button();
            cmdPlayerSprite.Size = new Size(81, 17);
            cmdPlayerSprite.Text = "Player Sprite";
            cmdPlayerSprite.ToolTip = "Change your sprite";
            RegisterControl("cmdPlayerSprite", cmdPlayerSprite);
            fralvl2Layout.Add(cmdPlayerSprite, 8, 48);
            cmdMapeditor = new Button();
            cmdMapeditor.Size = new Size(81, 17);
            cmdMapeditor.Text = "MapEditor";
            cmdMapeditor.ToolTip = "Edit the map";
            RegisterControl("cmdMapeditor", cmdMapeditor);
            fralvl2Layout.Add(cmdMapeditor, 8, 0);
            cmdWarpto = new Button();
            cmdWarpto.Size = new Size(81, 17);
            cmdWarpto.Text = "Warp To";
            cmdWarpto.ToolTip = "Warp yourself to";
            RegisterControl("cmdWarpto", cmdWarpto);
            fralvl2Layout.Add(cmdWarpto, 8, 16);
            cmdSetJail = new Button();
            cmdSetJail.Size = new Size(81, 17);
            cmdSetJail.Text = "Set Jail";
            cmdSetJail.ToolTip = "Set jail to your current tile";
            RegisterControl("cmdSetJail", cmdSetJail);
            fralvl2Layout.Add(cmdSetJail, 8, 146);
            fralvl1 = new GroupBox();
            fralvl1.Size = new Size(97, 111);
            fralvl1.Text = "Monitors";
            RegisterControl("fralvl1", fralvl1);
            root.Add(fralvl1, 8, 152);
            var fralvl1Layout = new PixelLayout();
            fralvl1.Content = fralvl1Layout;
            cmdKick = new Button();
            cmdKick.Size = new Size(81, 17);
            cmdKick.Text = "Kick";
            cmdKick.ToolTip = "Kick a player";
            RegisterControl("cmdKick", cmdKick);
            fralvl1Layout.Add(cmdKick, 8, 0);
            cmdJail = new Button();
            cmdJail.Size = new Size(81, 17);
            cmdJail.Text = "Jail";
            cmdJail.ToolTip = "Jail player";
            RegisterControl("cmdJail", cmdJail);
            fralvl1Layout.Add(cmdJail, 8, 18);
            cmdUnjail = new Button();
            cmdUnjail.Size = new Size(81, 17);
            cmdUnjail.Text = "Unjail";
            cmdUnjail.ToolTip = "Unjail player";
            RegisterControl("cmdUnjail", cmdUnjail);
            fralvl1Layout.Add(cmdUnjail, 8, 36);
            cmdMute = new Button();
            cmdMute.Size = new Size(81, 17);
            cmdMute.Text = "Mute";
            cmdMute.ToolTip = "Mute player";
            RegisterControl("cmdMute", cmdMute);
            fralvl1Layout.Add(cmdMute, 8, 54);
            cmdUnmute = new Button();
            cmdUnmute.Size = new Size(81, 17);
            cmdUnmute.Text = "Unmute";
            cmdUnmute.ToolTip = "Unmute player";
            RegisterControl("cmdUnmute", cmdUnmute);
            fralvl1Layout.Add(cmdUnmute, 8, 72);
            fralvl3 = new GroupBox();
            fralvl3.Size = new Size(97, 210);
            fralvl3.Text = "Developers";
            RegisterControl("fralvl3", fralvl3);
            root.Add(fralvl3, 120, 8);
            var fralvl3Layout = new PixelLayout();
            fralvl3.Content = fralvl3Layout;
            cmdNpcEditor = new Button();
            cmdNpcEditor.Size = new Size(81, 17);
            cmdNpcEditor.Text = "Npc Editor";
            cmdNpcEditor.ToolTip = "Edit the Npcs";
            RegisterControl("cmdNpcEditor", cmdNpcEditor);
            fralvl3Layout.Add(cmdNpcEditor, 8, 0);
            cmdItemEditor = new Button();
            cmdItemEditor.Size = new Size(81, 17);
            cmdItemEditor.Text = "Item Editor";
            cmdItemEditor.ToolTip = "Edit the Items";
            RegisterControl("cmdItemEditor", cmdItemEditor);
            fralvl3Layout.Add(cmdItemEditor, 8, 16);
            cmdShopEditor = new Button();
            cmdShopEditor.Size = new Size(81, 17);
            cmdShopEditor.Text = "ShopEditor";
            cmdShopEditor.ToolTip = "Edit the Shops";
            RegisterControl("cmdShopEditor", cmdShopEditor);
            fralvl3Layout.Add(cmdShopEditor, 8, 32);
            cmdSpellEditor = new Button();
            cmdSpellEditor.Size = new Size(81, 17);
            cmdSpellEditor.Text = "SpellEditor";
            cmdSpellEditor.ToolTip = "Edit the Spells";
            RegisterControl("cmdSpellEditor", cmdSpellEditor);
            fralvl3Layout.Add(cmdSpellEditor, 8, 48);
            cmdDelbanlist = new Button();
            cmdDelbanlist.Size = new Size(81, 17);
            cmdDelbanlist.Text = "Unban Player";
            cmdDelbanlist.ToolTip = "Unban Player.";
            RegisterControl("cmdDelbanlist", cmdDelbanlist);
            fralvl3Layout.Add(cmdDelbanlist, 7, 98);
            cmdKill = new Button();
            cmdKill.Size = new Size(81, 17);
            cmdKill.Text = "Kill";
            cmdKill.ToolTip = "Kill a Player";
            RegisterControl("cmdKill", cmdKill);
            fralvl3Layout.Add(cmdKill, 8, 168);
            cmbArrowEditor = new Button();
            cmbArrowEditor.Size = new Size(81, 17);
            cmbArrowEditor.Text = "Arrow Editor";
            cmbArrowEditor.ToolTip = "Edit the Spells";
            RegisterControl("cmbArrowEditor", cmbArrowEditor);
            fralvl3Layout.Add(cmbArrowEditor, 8, 82);
            cmbClassEditor = new Button();
            cmbClassEditor.Size = new Size(81, 17);
            cmbClassEditor.Text = "Class Editor";
            cmbClassEditor.ToolTip = "Edit the Spells";
            RegisterControl("cmbClassEditor", cmbClassEditor);
            fralvl3Layout.Add(cmbClassEditor, 8, 65);
            cmdQuestEditor = new Button();
            cmdQuestEditor.Size = new Size(81, 17);
            cmdQuestEditor.Text = "Quest Editor";
            cmdQuestEditor.ToolTip = "Edit NPC quest dialogue";
            RegisterControl("cmdQuestEditor", cmdQuestEditor);
            fralvl3Layout.Add(cmdQuestEditor, 8, 115);
            cmdBookEditor = new Button();
            cmdBookEditor.Size = new Size(81, 17);
            cmdBookEditor.Text = "Book Editor";
            cmdBookEditor.ToolTip = "Edit NPC quest dialogue";
            RegisterControl("cmdBookEditor", cmdBookEditor);
            fralvl3Layout.Add(cmdBookEditor, 8, 133);
            cmdEmoticonEditor = new Button();
            cmdEmoticonEditor.Size = new Size(81, 17);
            cmdEmoticonEditor.Text = "Emote Editor";
            cmdEmoticonEditor.ToolTip = "Edit NPC quest dialogue";
            RegisterControl("cmdEmoticonEditor", cmdEmoticonEditor);
            fralvl3Layout.Add(cmdEmoticonEditor, 8, 150);
            fralvl4 = new GroupBox();
            fralvl4.Size = new Size(97, 89);
            fralvl4.Text = "Server Owner";
            RegisterControl("fralvl4", fralvl4);
            root.Add(fralvl4, 120, 217);
            var fralvl4Layout = new PixelLayout();
            fralvl4.Content = fralvl4Layout;
            AccessLevel = new Label();
            AccessLevel.Size = new Size(77, 18);
            AccessLevel.Text = "Access Level";
            RegisterControl("AccessLevel", AccessLevel);
            fralvl4Layout.Add(AccessLevel, 8, 0);
            txtAccessLevel = new TextBox();
            txtAccessLevel.Size = new Size(81, 24);
            RegisterControl("txtAccessLevel", txtAccessLevel);
            fralvl4Layout.Add(txtAccessLevel, 8, 16);
            cmdSetAccess = new Button();
            cmdSetAccess.Size = new Size(81, 19);
            cmdSetAccess.Text = "Set Access";
            cmdSetAccess.ToolTip = "Set a players' admin access";
            RegisterControl("cmdSetAccess", cmdSetAccess);
            fralvl4Layout.Add(cmdSetAccess, 8, 48);
            fraSpriteNum = new GroupBox();
            fraSpriteNum.Size = new Size(97, 48);
            fraSpriteNum.Text = "Sprite #";
            RegisterControl("fraSpriteNum", fraSpriteNum);
            root.Add(fraSpriteNum, 8, 104);
            var fraSpriteNumLayout = new PixelLayout();
            fraSpriteNum.Content = fraSpriteNumLayout;
            txtSpriteNum = new TextBox();
            txtSpriteNum.Size = new Size(81, 24);
            RegisterControl("txtSpriteNum", txtSpriteNum);
            fraSpriteNumLayout.Add(txtSpriteNum, 8, 0);
            fraPlayer = new GroupBox();
            fraPlayer.Size = new Size(97, 48);
            fraPlayer.Text = "Player Name";
            RegisterControl("fraPlayer", fraPlayer);
            root.Add(fraPlayer, 8, 8);
            var fraPlayerLayout = new PixelLayout();
            fraPlayer.Content = fraPlayerLayout;
            txtPlayerName = new TextBox();
            txtPlayerName.Size = new Size(81, 23);
            RegisterControl("txtPlayerName", txtPlayerName);
            fraPlayerLayout.Add(txtPlayerName, 8, 0);
            fraMapNum = new GroupBox();
            fraMapNum.Size = new Size(97, 48);
            fraMapNum.Text = "Map Number";
            RegisterControl("fraMapNum", fraMapNum);
            root.Add(fraMapNum, 8, 56);
            var fraMapNumLayout = new PixelLayout();
            fraMapNum.Content = fraMapNumLayout;
            txtMapNum = new TextBox();
            txtMapNum.Size = new Size(81, 24);
            RegisterControl("txtMapNum", txtMapNum);
            fraMapNumLayout.Add(txtMapNum, 8, 0);
            InitializeTool();
        }
    }
}