using Eto.Drawing;
using Eto.Forms;

namespace XtremeWorlds.Client.Tools
{
    public partial class frmItemEditor : ToolForm
    {

        public readonly Label Label1;
        public readonly Label Label5;
        public readonly Label lblPic;
        public readonly DropDown cmbType;
        public readonly TextBox txtName;
        public readonly GroupBox fraEquipment;
        public readonly Label Label2;
        public readonly Label Label3;
        public readonly Label lblDurability;
        public readonly Label lblStrength;
        public readonly Slider scrlDurability;
        public readonly Slider scrlStrength;
        public readonly GroupBox fraVitals;
        public readonly Label Label4;
        public readonly Label lblVitalMod;
        public readonly Slider scrlVitalMod;
        public readonly Button cmdOk;
        public readonly Button cmdCancel;
        public readonly Slider scrlPic;
        public readonly SpritePreview picPic;
        public readonly UITimer tmrPic;
        public readonly GroupBox fraSpell;
        public readonly Label lblSpell;
        public readonly Label Label7;
        public readonly Label Label6;
        public readonly Label lblSpellName;
        public readonly Slider scrlSpell;
        public readonly GroupBox fraWarp;
        public readonly Label Label9;
        public readonly Label Label10;
        public readonly Label lblmapX;
        public readonly Label Label8;
        public readonly Label lblMapY;
        public readonly TextBox txtMap;
        public readonly Slider scrlMapX;
        public readonly Slider scrlMapY;
        public readonly GroupBox fraBook;
        public readonly Label lblBookIdCaption;
        public readonly Label lblBook;
        public readonly Slider scrlBook;

        public frmItemEditor() : base("item")
        {
            Title = "Item Editor";
            ClientSize = new Size(337, 285);
            Resizable = false;
            var root = new PixelLayout();
            Content = root;
            Label1 = new Label();
            Label1.Size = new Size(49, 25);
            Label1.Text = "Name";
            RegisterControl("Label1", Label1);
            root.Add(Label1, 8, 8);
            Label5 = new Label();
            Label5.Size = new Size(57, 25);
            Label5.Text = "Pic";
            RegisterControl("Label5", Label5);
            root.Add(Label5, 8, 40);
            lblPic = new Label();
            lblPic.Size = new Size(33, 25);
            lblPic.Text = "0";
            RegisterControl("lblPic", lblPic);
            root.Add(lblPic, 256, 40);
            cmbType = new DropDown();
            cmbType.Size = new Size(321, 26);
            cmbType.Items.Add("None");
            cmbType.Items.Add("Weapon");
            cmbType.Items.Add("Armor");
            cmbType.Items.Add("Helmet");
            cmbType.Items.Add("Shield");
            cmbType.Items.Add("Potion Add HP");
            cmbType.Items.Add("Potion Add MP");
            cmbType.Items.Add("Potion Add SP");
            cmbType.Items.Add("Potion Sub HP");
            cmbType.Items.Add("Potion Sub MP");
            cmbType.Items.Add("Potion Sub SP");
            cmbType.Items.Add("Key");
            cmbType.Items.Add("Currency");
            cmbType.Items.Add("Spell");
            cmbType.Items.Add("Warp");
            cmbType.Items.Add("Book");
            cmbType.SelectedIndex = 0;
            RegisterControl("cmbType", cmbType);
            root.Add(cmbType, 8, 88);
            txtName = new TextBox();
            txtName.Size = new Size(265, 26);
            RegisterControl("txtName", txtName);
            root.Add(txtName, 64, 8);
            fraEquipment = new GroupBox();
            fraEquipment.Size = new Size(321, 97);
            fraEquipment.Text = "Equipment Data";
            fraEquipment.Visible = false;
            RegisterControl("fraEquipment", fraEquipment);
            root.Add(fraEquipment, 8, 128);
            var fraEquipmentLayout = new PixelLayout();
            fraEquipment.Content = fraEquipmentLayout;
            Label2 = new Label();
            Label2.Size = new Size(73, 25);
            Label2.Text = "Durability";
            RegisterControl("Label2", Label2);
            fraEquipmentLayout.Add(Label2, 8, 16);
            Label3 = new Label();
            Label3.Size = new Size(65, 25);
            Label3.Text = "Strength";
            RegisterControl("Label3", Label3);
            fraEquipmentLayout.Add(Label3, 8, 48);
            lblDurability = new Label();
            lblDurability.Size = new Size(33, 25);
            lblDurability.Text = "1";
            RegisterControl("lblDurability", lblDurability);
            fraEquipmentLayout.Add(lblDurability, 280, 16);
            lblStrength = new Label();
            lblStrength.Size = new Size(33, 25);
            lblStrength.Text = "1";
            RegisterControl("lblStrength", lblStrength);
            fraEquipmentLayout.Add(lblStrength, 280, 48);
            scrlDurability = new Slider();
            scrlDurability.Size = new Size(193, 25);
            scrlDurability.MinValue = 0;
            scrlDurability.MaxValue = 255;
            scrlDurability.Value = 1;
            RegisterControl("scrlDurability", scrlDurability);
            fraEquipmentLayout.Add(scrlDurability, 88, 16);
            scrlStrength = new Slider();
            scrlStrength.Size = new Size(193, 25);
            scrlStrength.MinValue = 0;
            scrlStrength.MaxValue = 255;
            scrlStrength.Value = 1;
            RegisterControl("scrlStrength", scrlStrength);
            fraEquipmentLayout.Add(scrlStrength, 88, 48);
            fraVitals = new GroupBox();
            fraVitals.Size = new Size(321, 97);
            fraVitals.Text = "Vitals Data";
            fraVitals.Visible = false;
            RegisterControl("fraVitals", fraVitals);
            root.Add(fraVitals, 8, 128);
            var fraVitalsLayout = new PixelLayout();
            fraVitals.Content = fraVitalsLayout;
            Label4 = new Label();
            Label4.Size = new Size(73, 25);
            Label4.Text = "Vital Mod";
            RegisterControl("Label4", Label4);
            fraVitalsLayout.Add(Label4, 8, 8);
            lblVitalMod = new Label();
            lblVitalMod.Size = new Size(33, 25);
            lblVitalMod.Text = "1";
            RegisterControl("lblVitalMod", lblVitalMod);
            fraVitalsLayout.Add(lblVitalMod, 280, 8);
            scrlVitalMod = new Slider();
            scrlVitalMod.Size = new Size(193, 25);
            scrlVitalMod.MinValue = 0;
            scrlVitalMod.MaxValue = 255;
            scrlVitalMod.Value = 1;
            RegisterControl("scrlVitalMod", scrlVitalMod);
            fraVitalsLayout.Add(scrlVitalMod, 88, 8);
            cmdOk = new Button();
            cmdOk.Size = new Size(153, 33);
            cmdOk.Text = "Ok";
            RegisterControl("cmdOk", cmdOk);
            root.Add(cmdOk, 11, 240);
            cmdCancel = new Button();
            cmdCancel.Size = new Size(153, 33);
            cmdCancel.Text = "Cancel";
            RegisterControl("cmdCancel", cmdCancel);
            root.Add(cmdCancel, 176, 240);
            scrlPic = new Slider();
            scrlPic.Size = new Size(193, 25);
            scrlPic.MinValue = 0;
            scrlPic.MaxValue = 500;
            scrlPic.Value = 0;
            RegisterControl("scrlPic", scrlPic);
            root.Add(scrlPic, 64, 40);
            picPic = new SpritePreview();
            picPic.Size = new Size(32, 32);
            RegisterControl("picPic", picPic);
            root.Add(picPic, 296, 40);
            tmrPic = new UITimer();
            tmrPic.Interval = 0.050d;
            RegisterTimer(tmrPic);
            fraSpell = new GroupBox();
            fraSpell.Size = new Size(321, 97);
            fraSpell.Text = "Spell Data";
            fraSpell.Visible = false;
            RegisterControl("fraSpell", fraSpell);
            root.Add(fraSpell, 8, 128);
            var fraSpellLayout = new PixelLayout();
            fraSpell.Content = fraSpellLayout;
            lblSpell = new Label();
            lblSpell.Size = new Size(57, 25);
            lblSpell.Text = "1";
            RegisterControl("lblSpell", lblSpell);
            fraSpellLayout.Add(lblSpell, 256, 40);
            Label7 = new Label();
            Label7.Size = new Size(49, 25);
            Label7.Text = "Num";
            RegisterControl("Label7", Label7);
            fraSpellLayout.Add(Label7, 8, 40);
            Label6 = new Label();
            Label6.Size = new Size(73, 25);
            Label6.Text = "Name";
            RegisterControl("Label6", Label6);
            fraSpellLayout.Add(Label6, 8, 8);
            lblSpellName = new Label();
            lblSpellName.Size = new Size(225, 25);
            lblSpellName.Text = "";
            RegisterControl("lblSpellName", lblSpellName);
            fraSpellLayout.Add(lblSpellName, 88, 8);
            scrlSpell = new Slider();
            scrlSpell.Size = new Size(193, 25);
            scrlSpell.MinValue = 0;
            scrlSpell.MaxValue = 500;
            scrlSpell.Value = 1;
            RegisterControl("scrlSpell", scrlSpell);
            fraSpellLayout.Add(scrlSpell, 64, 40);
            fraWarp = new GroupBox();
            fraWarp.Size = new Size(321, 97);
            fraWarp.Text = "Warp Data";
            fraWarp.Visible = false;
            RegisterControl("fraWarp", fraWarp);
            root.Add(fraWarp, 8, 128);
            var fraWarpLayout = new PixelLayout();
            fraWarp.Content = fraWarpLayout;
            Label9 = new Label();
            Label9.Size = new Size(73, 25);
            Label9.Text = "Map";
            RegisterControl("Label9", Label9);
            fraWarpLayout.Add(Label9, 8, 8);
            Label10 = new Label();
            Label10.Size = new Size(49, 25);
            Label10.Text = "X";
            RegisterControl("Label10", Label10);
            fraWarpLayout.Add(Label10, 8, 48);
            lblmapX = new Label();
            lblmapX.Size = new Size(57, 25);
            lblmapX.Text = "1";
            RegisterControl("lblmapX", lblmapX);
            fraWarpLayout.Add(lblmapX, 96, 48);
            Label8 = new Label();
            Label8.Size = new Size(49, 25);
            Label8.Text = "Y";
            RegisterControl("Label8", Label8);
            fraWarpLayout.Add(Label8, 168, 48);
            lblMapY = new Label();
            lblMapY.Size = new Size(57, 25);
            lblMapY.Text = "1";
            RegisterControl("lblMapY", lblMapY);
            fraWarpLayout.Add(lblMapY, 256, 48);
            txtMap = new TextBox();
            txtMap.Size = new Size(193, 26);
            RegisterControl("txtMap", txtMap);
            fraWarpLayout.Add(txtMap, 64, 8);
            scrlMapX = new Slider();
            scrlMapX.Size = new Size(89, 25);
            scrlMapX.MinValue = 0;
            scrlMapX.MaxValue = 15;
            scrlMapX.Value = 0;
            RegisterControl("scrlMapX", scrlMapX);
            fraWarpLayout.Add(scrlMapX, 32, 48);
            scrlMapY = new Slider();
            scrlMapY.Size = new Size(89, 25);
            scrlMapY.MinValue = 0;
            scrlMapY.MaxValue = 11;
            scrlMapY.Value = 0;
            RegisterControl("scrlMapY", scrlMapY);
            fraWarpLayout.Add(scrlMapY, 192, 48);
            fraBook = new GroupBox();
            fraBook.Size = new Size(321, 97);
            fraBook.Text = "Book Data";
            fraBook.Visible = false;
            RegisterControl("fraBook", fraBook);
            root.Add(fraBook, 8, 128);
            var fraBookLayout = new PixelLayout();
            fraBook.Content = fraBookLayout;
            lblBookIdCaption = new Label();
            lblBookIdCaption.Size = new Size(100, 20);
            lblBookIdCaption.Text = "Book ID:";
            RegisterControl("lblBookIdCaption", lblBookIdCaption);
            fraBookLayout.Add(lblBookIdCaption, 16, 8);
            lblBook = new Label();
            lblBook.Size = new Size(60, 20);
            lblBook.Text = "1";
            RegisterControl("lblBook", lblBook);
            fraBookLayout.Add(lblBook, 130, 8);
            scrlBook = new Slider();
            scrlBook.Size = new Size(280, 25);
            scrlBook.MinValue = 1;
            scrlBook.MaxValue = 32767;
            scrlBook.Value = 1;
            RegisterControl("scrlBook", scrlBook);
            fraBookLayout.Add(scrlBook, 16, 40);
            InitializeTool();
        }
    }
}