using Eto.Drawing;
using Eto.Forms;

namespace XtremeWorlds.Client.Tools
{
    public partial class frmNpcEditor : ToolForm
    {

        public readonly Label lblSprite;
        public readonly Label Label5;
        public readonly Label Label1;
        public readonly Label Label2;
        public readonly Label lblRange;
        public readonly Label Label4;
        public readonly Label lblSTR;
        public readonly Label Label6;
        public readonly Label lblDEF;
        public readonly Label Label8;
        public readonly Label lblSPEED;
        public readonly Label Label10;
        public readonly Label lblMAGI;
        public readonly Label Label12;
        public readonly Label Label3;
        public readonly Label lblNum;
        public readonly Label Label9;
        public readonly Label Label11;
        public readonly Label lblItemName;
        public readonly Label Label7;
        public readonly Label lblValue;
        public readonly Label Label14;
        public readonly Label Label16;
        public readonly Label lbl17;
        public readonly Label Label15;
        public readonly Label Label13;
        public readonly Slider scrlSprite;
        public readonly TextBox txtName;
        public readonly DropDown cmbBehavior;
        public readonly Slider scrlRange;
        public readonly Slider scrlSTR;
        public readonly Slider scrlDEF;
        public readonly Slider scrlSPEED;
        public readonly Slider scrlMAGI;
        public readonly TextBox txtChance;
        public readonly Slider scrlNum;
        public readonly Slider scrlValue;
        public readonly Button cmdOk;
        public readonly Button cmdCancel;
        public readonly UITimer tmrSprite;
        public readonly TextBox txtAttackSay;
        public readonly TextBox txtSpawnSecs;
        public readonly DropDown cmbShop;
        public readonly TextBox txtGiveEXP;
        public readonly TextBox txtMaxHP;
        public readonly SpritePreview imgSprite;
        public readonly DropDown cmbQuestId;

        public frmNpcEditor() : base("npc")
        {
            Title = "Npc Editor";
            ClientSize = new Size(355, 630);
            Resizable = false;
            var root = new PixelLayout();
            Content = root;
            lblSprite = new Label();
            lblSprite.Size = new Size(33, 25);
            lblSprite.Text = "0";
            RegisterControl("lblSprite", lblSprite);
            root.Add(lblSprite, 264, 80);
            Label5 = new Label();
            Label5.Size = new Size(57, 25);
            Label5.Text = "Sprite";
            RegisterControl("Label5", Label5);
            root.Add(Label5, 16, 80);
            Label1 = new Label();
            Label1.Size = new Size(49, 25);
            Label1.Text = "Name";
            RegisterControl("Label1", Label1);
            root.Add(Label1, 8, 8);
            Label2 = new Label();
            Label2.Size = new Size(73, 25);
            Label2.Text = "Behavior";
            RegisterControl("Label2", Label2);
            root.Add(Label2, 16, 280);
            lblRange = new Label();
            lblRange.Size = new Size(33, 25);
            lblRange.Text = "0";
            RegisterControl("lblRange", lblRange);
            root.Add(lblRange, 264, 112);
            Label4 = new Label();
            Label4.Size = new Size(57, 25);
            Label4.Text = "Range";
            RegisterControl("Label4", Label4);
            root.Add(Label4, 16, 112);
            lblSTR = new Label();
            lblSTR.Size = new Size(33, 25);
            lblSTR.Text = "0";
            RegisterControl("lblSTR", lblSTR);
            root.Add(lblSTR, 264, 144);
            Label6 = new Label();
            Label6.Size = new Size(57, 25);
            Label6.Text = "STR";
            RegisterControl("Label6", Label6);
            root.Add(Label6, 16, 144);
            lblDEF = new Label();
            lblDEF.Size = new Size(33, 25);
            lblDEF.Text = "0";
            RegisterControl("lblDEF", lblDEF);
            root.Add(lblDEF, 264, 176);
            Label8 = new Label();
            Label8.Size = new Size(57, 25);
            Label8.Text = "DEF";
            RegisterControl("Label8", Label8);
            root.Add(Label8, 16, 176);
            lblSPEED = new Label();
            lblSPEED.Size = new Size(33, 25);
            lblSPEED.Text = "0";
            RegisterControl("lblSPEED", lblSPEED);
            root.Add(lblSPEED, 264, 208);
            Label10 = new Label();
            Label10.Size = new Size(57, 25);
            Label10.Text = "SPD";
            RegisterControl("Label10", Label10);
            root.Add(Label10, 16, 208);
            lblMAGI = new Label();
            lblMAGI.Size = new Size(33, 25);
            lblMAGI.Text = "0";
            RegisterControl("lblMAGI", lblMAGI);
            root.Add(lblMAGI, 264, 240);
            Label12 = new Label();
            Label12.Size = new Size(57, 25);
            Label12.Text = "MAGI";
            RegisterControl("Label12", Label12);
            root.Add(Label12, 16, 240);
            Label3 = new Label();
            Label3.Size = new Size(193, 25);
            Label3.Text = "Drop Item Chance 1 out of";
            RegisterControl("Label3", Label3);
            root.Add(Label3, 16, 320);
            lblNum = new Label();
            lblNum.Size = new Size(33, 25);
            lblNum.Text = "0";
            RegisterControl("lblNum", lblNum);
            root.Add(lblNum, 304, 432);
            Label9 = new Label();
            Label9.Size = new Size(57, 25);
            Label9.Text = "Num";
            RegisterControl("Label9", Label9);
            root.Add(Label9, 16, 432);
            Label11 = new Label();
            Label11.Size = new Size(41, 25);
            Label11.Text = "Item";
            RegisterControl("Label11", Label11);
            root.Add(Label11, 16, 400);
            lblItemName = new Label();
            lblItemName.Size = new Size(273, 25);
            lblItemName.Text = "";
            RegisterControl("lblItemName", lblItemName);
            root.Add(lblItemName, 64, 400);
            Label7 = new Label();
            Label7.Size = new Size(49, 25);
            Label7.Text = "Value";
            RegisterControl("Label7", Label7);
            root.Add(Label7, 16, 464);
            lblValue = new Label();
            lblValue.Size = new Size(33, 25);
            lblValue.Text = "0";
            RegisterControl("lblValue", lblValue);
            root.Add(lblValue, 304, 464);
            Label14 = new Label();
            Label14.Size = new Size(49, 25);
            Label14.Text = "Say";
            RegisterControl("Label14", Label14);
            root.Add(Label14, 8, 40);
            Label16 = new Label();
            Label16.Size = new Size(193, 25);
            Label16.Text = "Spawn Rate (in seconds)";
            RegisterControl("Label16", Label16);
            root.Add(Label16, 16, 352);
            lbl17 = new Label();
            lbl17.Size = new Size(153, 25);
            lbl17.Text = "Shopkeeper's Shop";
            lbl17.Visible = false;
            RegisterControl("lbl17", lbl17);
            root.Add(lbl17, 8, 544);
            Label15 = new Label();
            Label15.Size = new Size(81, 25);
            Label15.Text = "Exp Given";
            RegisterControl("Label15", Label15);
            root.Add(Label15, 168, 504);
            Label13 = new Label();
            Label13.Size = new Size(65, 25);
            Label13.Text = "Start HP";
            RegisterControl("Label13", Label13);
            root.Add(Label13, 8, 504);
            scrlSprite = new Slider();
            scrlSprite.Size = new Size(193, 25);
            scrlSprite.MinValue = 0;
            scrlSprite.MaxValue = 500;
            scrlSprite.Value = 0;
            RegisterControl("scrlSprite", scrlSprite);
            root.Add(scrlSprite, 74, 79);
            txtName = new TextBox();
            txtName.Size = new Size(283, 26);
            RegisterControl("txtName", txtName);
            root.Add(txtName, 64, 8);
            cmbBehavior = new DropDown();
            cmbBehavior.Size = new Size(241, 26);
            cmbBehavior.Items.Add("Attack on sight");
            cmbBehavior.Items.Add("Attack when attacked");
            cmbBehavior.Items.Add("Friendly");
            cmbBehavior.Items.Add("Shop keeper");
            cmbBehavior.Items.Add("Guard");
            cmbBehavior.SelectedIndex = 0;
            RegisterControl("cmbBehavior", cmbBehavior);
            root.Add(cmbBehavior, 96, 280);
            scrlRange = new Slider();
            scrlRange.Size = new Size(193, 25);
            scrlRange.MinValue = 0;
            scrlRange.MaxValue = 255;
            scrlRange.Value = 1;
            RegisterControl("scrlRange", scrlRange);
            root.Add(scrlRange, 72, 112);
            scrlSTR = new Slider();
            scrlSTR.Size = new Size(193, 25);
            scrlSTR.MinValue = 0;
            scrlSTR.MaxValue = 255;
            scrlSTR.Value = 0;
            RegisterControl("scrlSTR", scrlSTR);
            root.Add(scrlSTR, 72, 144);
            scrlDEF = new Slider();
            scrlDEF.Size = new Size(193, 25);
            scrlDEF.MinValue = 0;
            scrlDEF.MaxValue = 255;
            scrlDEF.Value = 0;
            RegisterControl("scrlDEF", scrlDEF);
            root.Add(scrlDEF, 72, 176);
            scrlSPEED = new Slider();
            scrlSPEED.Size = new Size(193, 25);
            scrlSPEED.MinValue = 0;
            scrlSPEED.MaxValue = 255;
            scrlSPEED.Value = 0;
            RegisterControl("scrlSPEED", scrlSPEED);
            root.Add(scrlSPEED, 72, 208);
            scrlMAGI = new Slider();
            scrlMAGI.Size = new Size(193, 25);
            scrlMAGI.MinValue = 0;
            scrlMAGI.MaxValue = 255;
            scrlMAGI.Value = 0;
            RegisterControl("scrlMAGI", scrlMAGI);
            root.Add(scrlMAGI, 72, 240);
            txtChance = new TextBox();
            txtChance.Size = new Size(121, 26);
            txtChance.Text = "0";
            RegisterControl("txtChance", txtChance);
            root.Add(txtChance, 216, 320);
            scrlNum = new Slider();
            scrlNum.Size = new Size(225, 25);
            scrlNum.MinValue = 0;
            scrlNum.MaxValue = 500;
            scrlNum.Value = 1;
            RegisterControl("scrlNum", scrlNum);
            root.Add(scrlNum, 72, 432);
            scrlValue = new Slider();
            scrlValue.Size = new Size(225, 25);
            scrlValue.MinValue = 0;
            scrlValue.MaxValue = 255;
            scrlValue.Value = 1;
            RegisterControl("scrlValue", scrlValue);
            root.Add(scrlValue, 72, 464);
            cmdOk = new Button();
            cmdOk.Size = new Size(161, 41);
            cmdOk.Text = "Ok";
            RegisterControl("cmdOk", cmdOk);
            root.Add(cmdOk, 8, 584);
            cmdCancel = new Button();
            cmdCancel.Size = new Size(161, 41);
            cmdCancel.Text = "Cancel";
            RegisterControl("cmdCancel", cmdCancel);
            root.Add(cmdCancel, 176, 584);
            tmrSprite = new UITimer();
            tmrSprite.Interval = 0.050d;
            RegisterTimer(tmrSprite);
            txtAttackSay = new TextBox();
            txtAttackSay.Size = new Size(284, 26);
            RegisterControl("txtAttackSay", txtAttackSay);
            root.Add(txtAttackSay, 64, 40);
            txtSpawnSecs = new TextBox();
            txtSpawnSecs.Size = new Size(121, 26);
            txtSpawnSecs.Text = "0";
            RegisterControl("txtSpawnSecs", txtSpawnSecs);
            root.Add(txtSpawnSecs, 216, 352);
            cmbShop = new DropDown();
            cmbShop.Size = new Size(169, 26);
            cmbShop.Visible = false;
            RegisterControl("cmbShop", cmbShop);
            root.Add(cmbShop, 168, 544);
            txtGiveEXP = new TextBox();
            txtGiveEXP.Size = new Size(73, 26);
            RegisterControl("txtGiveEXP", txtGiveEXP);
            root.Add(txtGiveEXP, 256, 504);
            txtMaxHP = new TextBox();
            txtMaxHP.Size = new Size(81, 26);
            RegisterControl("txtMaxHP", txtMaxHP);
            root.Add(txtMaxHP, 80, 504);
            imgSprite = new SpritePreview();
            imgSprite.Size = new Size(48, 64);
            RegisterControl("imgSprite", imgSprite);
            root.Add(imgSprite, 305, 78);
            cmbQuestId = new DropDown();
            cmbQuestId.Size = new Size(169, 26);
            cmbQuestId.Visible = false;
            RegisterControl("cmbQuestId", cmbQuestId);
            root.Add(cmbQuestId, 168, 544);
            InitializeTool();
        }
    }
}