using Eto.Drawing;
using Eto.Forms;

namespace XtremeWorlds.Client.Tools
{
    public partial class frmQuestEditor : ToolForm
    {

        public readonly Label Label10;
        public readonly TextBox txtName;
        public readonly Label Label9;
        public readonly DropDown cmbNpc;
        public readonly Label Label12;
        public readonly TextBox txtNpcSay;
        public readonly Label Label11;
        public readonly TextBox txtCompleted;
        public readonly Label Label15;
        public readonly TextBox txtHadItem;
        public readonly Label Label13;
        public readonly TextBox txtNotReady;
        public readonly Label Label14;
        public readonly TextBox txtNotHadItem;
        public readonly Label Label6;
        public readonly DropDown cmbClassReq;
        public readonly Label Label16;
        public readonly Slider scrlLevel;
        public readonly Label lblLevel;
        public readonly Label Label27;
        public readonly DropDown cmbQuest;
        public readonly Label Label17;
        public readonly DropDown cmbItemHas_0;
        public readonly Label Label18;
        public readonly TextBox txtItemHasValue_0;
        public readonly Label Label1;
        public readonly DropDown cmbItemGet;
        public readonly Label Label3;
        public readonly TextBox txtItemGetValue;
        public readonly Label Label5;
        public readonly TextBox txtExpGet;
        public readonly Button cmdCancel;
        public readonly Button cmdSubmit;
        public readonly CheckBox chkHealth;
        public readonly CheckBox chkMana;
        public readonly CheckBox chkStamina;
        public readonly CheckBox chkOnce;

        public frmQuestEditor() : base("quest")
        {
            Title = "Quest Editor";
            ClientSize = new Size(620, 616);
            Resizable = false;
            var root = new PixelLayout();
            Content = root;
            Label10 = new Label();
            Label10.Size = new Size(168, 20);
            Label10.Text = "Quest name";
            RegisterControl("Label10", Label10);
            root.Add(Label10, 24, 36);
            txtName = new TextBox();
            txtName.Size = new Size(392, 24);
            txtName.MaxLength = 240;
            RegisterControl("txtName", txtName);
            root.Add(txtName, 200, 32);
            Label9 = new Label();
            Label9.Size = new Size(168, 20);
            Label9.Text = "NPC";
            RegisterControl("Label9", Label9);
            root.Add(Label9, 24, 68);
            cmbNpc = new DropDown();
            cmbNpc.Size = new Size(392, 24);
            RegisterControl("cmbNpc", cmbNpc);
            root.Add(cmbNpc, 200, 64);
            Label12 = new Label();
            Label12.Size = new Size(168, 20);
            Label12.Text = "NPC says";
            RegisterControl("Label12", Label12);
            root.Add(Label12, 24, 100);
            txtNpcSay = new TextBox();
            txtNpcSay.Size = new Size(392, 24);
            txtNpcSay.MaxLength = 255;
            RegisterControl("txtNpcSay", txtNpcSay);
            root.Add(txtNpcSay, 200, 96);
            Label11 = new Label();
            Label11.Size = new Size(168, 20);
            Label11.Text = "Completed";
            RegisterControl("Label11", Label11);
            root.Add(Label11, 24, 132);
            txtCompleted = new TextBox();
            txtCompleted.Size = new Size(392, 24);
            txtCompleted.MaxLength = 255;
            RegisterControl("txtCompleted", txtCompleted);
            root.Add(txtCompleted, 200, 128);
            Label15 = new Label();
            Label15.Size = new Size(168, 20);
            Label15.Text = "Already done";
            RegisterControl("Label15", Label15);
            root.Add(Label15, 24, 164);
            txtHadItem = new TextBox();
            txtHadItem.Size = new Size(392, 24);
            txtHadItem.MaxLength = 255;
            RegisterControl("txtHadItem", txtHadItem);
            root.Add(txtHadItem, 200, 160);
            Label13 = new Label();
            Label13.Size = new Size(168, 20);
            Label13.Text = "Not ready";
            RegisterControl("Label13", Label13);
            root.Add(Label13, 24, 196);
            txtNotReady = new TextBox();
            txtNotReady.Size = new Size(392, 24);
            txtNotReady.MaxLength = 255;
            RegisterControl("txtNotReady", txtNotReady);
            root.Add(txtNotReady, 200, 192);
            Label14 = new Label();
            Label14.Size = new Size(168, 20);
            Label14.Text = "Not had item";
            RegisterControl("Label14", Label14);
            root.Add(Label14, 24, 228);
            txtNotHadItem = new TextBox();
            txtNotHadItem.Size = new Size(392, 24);
            txtNotHadItem.MaxLength = 255;
            RegisterControl("txtNotHadItem", txtNotHadItem);
            root.Add(txtNotHadItem, 200, 224);
            Label6 = new Label();
            Label6.Size = new Size(168, 20);
            Label6.Text = "Class requirement";
            RegisterControl("Label6", Label6);
            root.Add(Label6, 24, 260);
            cmbClassReq = new DropDown();
            cmbClassReq.Size = new Size(392, 24);
            RegisterControl("cmbClassReq", cmbClassReq);
            root.Add(cmbClassReq, 200, 256);
            Label16 = new Label();
            Label16.Size = new Size(168, 20);
            Label16.Text = "Level requirement";
            RegisterControl("Label16", Label16);
            root.Add(Label16, 24, 292);
            scrlLevel = new Slider();
            scrlLevel.Size = new Size(332, 20);
            scrlLevel.MinValue = 0;
            scrlLevel.MaxValue = 32767;
            scrlLevel.Value = 0;
            RegisterControl("scrlLevel", scrlLevel);
            root.Add(scrlLevel, 200, 288);
            lblLevel = new Label();
            lblLevel.Size = new Size(52, 20);
            lblLevel.Text = "0";
            RegisterControl("lblLevel", lblLevel);
            root.Add(lblLevel, 540, 288);
            Label27 = new Label();
            Label27.Size = new Size(168, 20);
            Label27.Text = "On completion, unlock";
            RegisterControl("Label27", Label27);
            root.Add(Label27, 24, 324);
            cmbQuest = new DropDown();
            cmbQuest.Size = new Size(392, 24);
            RegisterControl("cmbQuest", cmbQuest);
            root.Add(cmbQuest, 200, 320);
            Label17 = new Label();
            Label17.Size = new Size(168, 20);
            Label17.Text = "Required item";
            RegisterControl("Label17", Label17);
            root.Add(Label17, 24, 356);
            cmbItemHas_0 = new DropDown();
            cmbItemHas_0.Size = new Size(392, 24);
            RegisterControl("cmbItemHas_0", cmbItemHas_0);
            root.Add(cmbItemHas_0, 200, 352);
            Label18 = new Label();
            Label18.Size = new Size(168, 20);
            Label18.Text = "Required quantity";
            RegisterControl("Label18", Label18);
            root.Add(Label18, 24, 388);
            txtItemHasValue_0 = new TextBox();
            txtItemHasValue_0.Size = new Size(392, 24);
            txtItemHasValue_0.Text = "0";
            txtItemHasValue_0.MaxLength = 9;
            RegisterControl("txtItemHasValue_0", txtItemHasValue_0);
            root.Add(txtItemHasValue_0, 200, 384);
            Label1 = new Label();
            Label1.Size = new Size(168, 20);
            Label1.Text = "Reward item";
            RegisterControl("Label1", Label1);
            root.Add(Label1, 24, 420);
            cmbItemGet = new DropDown();
            cmbItemGet.Size = new Size(392, 24);
            RegisterControl("cmbItemGet", cmbItemGet);
            root.Add(cmbItemGet, 200, 416);
            Label3 = new Label();
            Label3.Size = new Size(168, 20);
            Label3.Text = "Reward quantity";
            RegisterControl("Label3", Label3);
            root.Add(Label3, 24, 452);
            txtItemGetValue = new TextBox();
            txtItemGetValue.Size = new Size(392, 24);
            txtItemGetValue.Text = "0";
            txtItemGetValue.MaxLength = 9;
            RegisterControl("txtItemGetValue", txtItemGetValue);
            root.Add(txtItemGetValue, 200, 448);
            Label5 = new Label();
            Label5.Size = new Size(168, 20);
            Label5.Text = "Experience reward";
            RegisterControl("Label5", Label5);
            root.Add(Label5, 24, 484);
            txtExpGet = new TextBox();
            txtExpGet.Size = new Size(392, 24);
            txtExpGet.Text = "0";
            txtExpGet.MaxLength = 9;
            RegisterControl("txtExpGet", txtExpGet);
            root.Add(txtExpGet, 200, 480);
            cmdCancel = new Button();
            cmdCancel.Size = new Size(284, 32);
            cmdCancel.Text = "Cancel";
            RegisterControl("cmdCancel", cmdCancel);
            root.Add(cmdCancel, 320, 568);
            cmdSubmit = new Button();
            cmdSubmit.Size = new Size(284, 32);
            cmdSubmit.Text = "Save";
            RegisterControl("cmdSubmit", cmdSubmit);
            root.Add(cmdSubmit, 16, 568);
            chkHealth = new CheckBox();
            chkHealth.Size = new Size(140, 24);
            chkHealth.Text = "Full Health";
            chkHealth.Checked = false;
            RegisterControl("chkHealth", chkHealth);
            root.Add(chkHealth, 24, 532);
            chkMana = new CheckBox();
            chkMana.Size = new Size(140, 24);
            chkMana.Text = "Full Magic";
            chkMana.Checked = false;
            RegisterControl("chkMana", chkMana);
            root.Add(chkMana, 172, 532);
            chkStamina = new CheckBox();
            chkStamina.Size = new Size(140, 24);
            chkStamina.Text = "Full Stamina";
            chkStamina.Checked = false;
            RegisterControl("chkStamina", chkStamina);
            root.Add(chkStamina, 320, 532);
            chkOnce = new CheckBox();
            chkOnce.Size = new Size(140, 24);
            chkOnce.Text = "Once";
            chkOnce.Checked = false;
            RegisterControl("chkOnce", chkOnce);
            root.Add(chkOnce, 468, 532);
            InitializeTool();
        }
    }
}