using Eto.Drawing;
using Eto.Forms;

namespace XtremeWorlds.Client.Tools
{
    public partial class frmShopEditor : ToolForm
    {

        public readonly Label Label14;
        public readonly Label Label1;
        public readonly Label Label2;
        public readonly Label Label3;
        public readonly Label Label4;
        public readonly Label Label5;
        public readonly Label Label6;
        public readonly Label Label7;
        public readonly Label Label8;
        public readonly TextBox txtJoinSay;
        public readonly TextBox txtName;
        public readonly TextBox txtLeaveSay;
        public readonly ListBox lstTradeItem;
        public readonly DropDown cmbItemGive;
        public readonly TextBox txtItemGiveValue;
        public readonly Button cmdCancel;
        public readonly Button cmdOk;
        public readonly DropDown cmbItemGet;
        public readonly TextBox txtItemGetValue;
        public readonly Button cmdUpdate;
        public readonly CheckBox chkFixesItems;
        public readonly TextBox txtItem2GiveValue;
        public readonly DropDown cmbitem2Give;

        public frmShopEditor() : base("shop")
        {
            Title = "Shop Editor";
            ClientSize = new Size(369, 543);
            Resizable = false;
            var root = new PixelLayout();
            Content = root;
            Label14 = new Label();
            Label14.Size = new Size(81, 25);
            Label14.Text = "Join Say";
            RegisterControl("Label14", Label14);
            root.Add(Label14, 8, 40);
            Label1 = new Label();
            Label1.Size = new Size(81, 25);
            Label1.Text = "Name";
            RegisterControl("Label1", Label1);
            root.Add(Label1, 8, 8);
            Label2 = new Label();
            Label2.Size = new Size(81, 25);
            Label2.Text = "Leave Say";
            RegisterControl("Label2", Label2);
            root.Add(Label2, 8, 72);
            Label3 = new Label();
            Label3.Size = new Size(81, 25);
            Label3.Text = "Item Give";
            RegisterControl("Label3", Label3);
            root.Add(Label3, 8, 152);
            Label4 = new Label();
            Label4.Size = new Size(81, 25);
            Label4.Text = "Value";
            RegisterControl("Label4", Label4);
            root.Add(Label4, 8, 184);
            Label5 = new Label();
            Label5.Size = new Size(81, 25);
            Label5.Text = "Item Get";
            RegisterControl("Label5", Label5);
            root.Add(Label5, 8, 296);
            Label6 = new Label();
            Label6.Size = new Size(81, 25);
            Label6.Text = "Value";
            RegisterControl("Label6", Label6);
            root.Add(Label6, 8, 328);
            Label7 = new Label();
            Label7.Size = new Size(81, 25);
            Label7.Text = "Value 2";
            RegisterControl("Label7", Label7);
            root.Add(Label7, 8, 256);
            Label8 = new Label();
            Label8.Size = new Size(81, 25);
            Label8.Text = "Item Give 2";
            RegisterControl("Label8", Label8);
            root.Add(Label8, 8, 224);
            txtJoinSay = new TextBox();
            txtJoinSay.Size = new Size(265, 26);
            txtJoinSay.ToolTip = "This is what the shop will say when it opens.";
            RegisterControl("txtJoinSay", txtJoinSay);
            root.Add(txtJoinSay, 96, 40);
            txtName = new TextBox();
            txtName.Size = new Size(265, 26);
            txtName.ToolTip = "This is the name of the shop.";
            RegisterControl("txtName", txtName);
            root.Add(txtName, 96, 8);
            txtLeaveSay = new TextBox();
            txtLeaveSay.Size = new Size(265, 26);
            txtLeaveSay.ToolTip = "This is the goodbye message that will appear after a player is done shopping.";
            RegisterControl("txtLeaveSay", txtLeaveSay);
            root.Add(txtLeaveSay, 96, 72);
            lstTradeItem = new ListBox();
            lstTradeItem.Size = new Size(353, 116);
            lstTradeItem.Items.Add("1.");
            lstTradeItem.Items.Add("2.");
            lstTradeItem.Items.Add("3.");
            lstTradeItem.Items.Add("4.");
            lstTradeItem.Items.Add("5.");
            lstTradeItem.Items.Add("6.");
            lstTradeItem.Items.Add("7.");
            lstTradeItem.Items.Add("8.");
            lstTradeItem.SelectedIndex = 0;
            RegisterControl("lstTradeItem", lstTradeItem);
            root.Add(lstTradeItem, 8, 368);
            cmbItemGive = new DropDown();
            cmbItemGive.Size = new Size(265, 26);
            RegisterControl("cmbItemGive", cmbItemGive);
            root.Add(cmbItemGive, 96, 152);
            txtItemGiveValue = new TextBox();
            txtItemGiveValue.Size = new Size(89, 26);
            txtItemGiveValue.Text = "1";
            RegisterControl("txtItemGiveValue", txtItemGiveValue);
            root.Add(txtItemGiveValue, 96, 184);
            cmdCancel = new Button();
            cmdCancel.Size = new Size(169, 41);
            cmdCancel.Text = "Cancel";
            RegisterControl("cmdCancel", cmdCancel);
            root.Add(cmdCancel, 192, 496);
            cmdOk = new Button();
            cmdOk.Size = new Size(169, 41);
            cmdOk.Text = "Ok";
            RegisterControl("cmdOk", cmdOk);
            root.Add(cmdOk, 8, 496);
            cmbItemGet = new DropDown();
            cmbItemGet.Size = new Size(265, 26);
            RegisterControl("cmbItemGet", cmbItemGet);
            root.Add(cmbItemGet, 96, 296);
            txtItemGetValue = new TextBox();
            txtItemGetValue.Size = new Size(89, 26);
            txtItemGetValue.Text = "1";
            RegisterControl("txtItemGetValue", txtItemGetValue);
            root.Add(txtItemGetValue, 96, 328);
            cmdUpdate = new Button();
            cmdUpdate.Size = new Size(161, 25);
            cmdUpdate.Text = "Update ";
            RegisterControl("cmdUpdate", cmdUpdate);
            root.Add(cmdUpdate, 200, 328);
            chkFixesItems = new CheckBox();
            chkFixesItems.Size = new Size(353, 25);
            chkFixesItems.Text = "Fixes Items";
            chkFixesItems.Checked = false;
            chkFixesItems.ToolTip = "Check this box if you wat the shop to be able to fix items.";
            RegisterControl("chkFixesItems", chkFixesItems);
            root.Add(chkFixesItems, 8, 112);
            txtItem2GiveValue = new TextBox();
            txtItem2GiveValue.Size = new Size(89, 26);
            txtItem2GiveValue.Text = "1";
            txtItem2GiveValue.Enabled = false;
            RegisterControl("txtItem2GiveValue", txtItem2GiveValue);
            root.Add(txtItem2GiveValue, 96, 256);
            cmbitem2Give = new DropDown();
            cmbitem2Give.Size = new Size(265, 26);
            cmbitem2Give.Enabled = false;
            RegisterControl("cmbitem2Give", cmbitem2Give);
            root.Add(cmbitem2Give, 96, 224);
            InitializeTool();
        }
    }
}