using Eto.Drawing;
using Eto.Forms;

namespace XtremeWorlds.Client.Tools
{
    public partial class frmSignEditor : ToolForm
    {

        public readonly Label Label1;
        public readonly Label Label2;
        public readonly Label Label3;
        public readonly Label Label4;
        public readonly Label Label5;
        public readonly TextBox txtSignName;
        public readonly TextBox txtSignLine3;
        public readonly TextBox txtSignLine2;
        public readonly TextBox txtSignLine1;
        public readonly RadioButton optWooden;
        public readonly RadioButton optScroll;
        public readonly Button cmdOK;
        public readonly Button cmdCancel;
        public readonly Button cmdPrev;
        public readonly Panel picSign;
        public readonly Label lblNameBtm;
        public readonly Label lblNameTop;
        public readonly Label lblLine3Btm;
        public readonly Label lblLine2Btm;
        public readonly Label lblLine1Btm;
        public readonly Panel Line1;
        public readonly Label lblLine3Top;
        public readonly Label lblLine2Top;
        public readonly Label lblLine1Top;
        public readonly Label lblexit;

        public frmSignEditor() : base("sign")
        {
            Title = "Sign Editor";
            ClientSize = new Size(201, 505);
            Resizable = false;
            var root = new PixelLayout();
            Content = root;
            Label1 = new Label();
            Label1.Size = new Size(137, 17);
            Label1.Text = "Sign Name";
            RegisterControl("Label1", Label1);
            root.Add(Label1, 32, 144);
            Label2 = new Label();
            Label2.Size = new Size(137, 17);
            Label2.Text = "Background";
            RegisterControl("Label2", Label2);
            root.Add(Label2, 32, 200);
            Label3 = new Label();
            Label3.Size = new Size(137, 17);
            Label3.Text = "Line 3";
            RegisterControl("Label3", Label3);
            root.Add(Label3, 32, 384);
            Label4 = new Label();
            Label4.Size = new Size(137, 17);
            Label4.Text = "Line 2";
            RegisterControl("Label4", Label4);
            root.Add(Label4, 32, 328);
            Label5 = new Label();
            Label5.Size = new Size(137, 17);
            Label5.Text = "Line 1";
            RegisterControl("Label5", Label5);
            root.Add(Label5, 32, 272);
            txtSignName = new TextBox();
            txtSignName.Size = new Size(137, 25);
            txtSignName.Text = "Name";
            RegisterControl("txtSignName", txtSignName);
            root.Add(txtSignName, 32, 168);
            txtSignLine3 = new TextBox();
            txtSignLine3.Size = new Size(137, 25);
            RegisterControl("txtSignLine3", txtSignLine3);
            root.Add(txtSignLine3, 32, 408);
            txtSignLine2 = new TextBox();
            txtSignLine2.Size = new Size(137, 25);
            RegisterControl("txtSignLine2", txtSignLine2);
            root.Add(txtSignLine2, 32, 352);
            txtSignLine1 = new TextBox();
            txtSignLine1.Size = new Size(137, 25);
            RegisterControl("txtSignLine1", txtSignLine1);
            root.Add(txtSignLine1, 32, 296);
            optWooden = new RadioButton();
            optWooden.Size = new Size(137, 17);
            optWooden.Text = "Wooden Sign";
            optWooden.Checked = true;
            RegisterControl("optWooden", optWooden);
            root.Add(optWooden, 32, 224);
            optScroll = new RadioButton(optWooden);
            optScroll.Size = new Size(137, 17);
            optScroll.Text = "Parchment / Scroll";
            optScroll.Checked = false;
            RegisterControl("optScroll", optScroll);
            root.Add(optScroll, 32, 248);
            cmdOK = new Button();
            cmdOK.Size = new Size(65, 25);
            cmdOK.Text = "&OK";
            RegisterControl("cmdOK", cmdOK);
            root.Add(cmdOK, 32, 472);
            cmdCancel = new Button();
            cmdCancel.Size = new Size(65, 25);
            cmdCancel.Text = "&Cancel";
            RegisterControl("cmdCancel", cmdCancel);
            root.Add(cmdCancel, 104, 472);
            cmdPrev = new Button();
            cmdPrev.Size = new Size(137, 25);
            cmdPrev.Text = "&Preview Sign";
            RegisterControl("cmdPrev", cmdPrev);
            root.Add(cmdPrev, 32, 440);
            picSign = new Panel();
            picSign.Size = new Size(185, 121);
            RegisterControl("picSign", picSign);
            root.Add(picSign, 8, 8);
            var picSignLayout = new PixelLayout();
            picSign.Content = picSignLayout;
            lblNameBtm = new Label();
            lblNameBtm.Size = new Size(185, 25);
            lblNameBtm.Text = "Name";
            RegisterControl("lblNameBtm", lblNameBtm);
            picSignLayout.Add(lblNameBtm, 0, 11);
            lblNameTop = new Label();
            lblNameTop.Size = new Size(185, 25);
            lblNameTop.Text = "Name";
            RegisterControl("lblNameTop", lblNameTop);
            picSignLayout.Add(lblNameTop, 3, 8);
            lblLine3Btm = new Label();
            lblLine3Btm.Size = new Size(185, 25);
            lblLine3Btm.Text = "Line3";
            RegisterControl("lblLine3Btm", lblLine3Btm);
            picSignLayout.Add(lblLine3Btm, 0, 70);
            lblLine2Btm = new Label();
            lblLine2Btm.Size = new Size(185, 25);
            lblLine2Btm.Text = "Line2";
            RegisterControl("lblLine2Btm", lblLine2Btm);
            picSignLayout.Add(lblLine2Btm, 0, 54);
            lblLine1Btm = new Label();
            lblLine1Btm.Size = new Size(185, 25);
            lblLine1Btm.Text = "Line1";
            RegisterControl("lblLine1Btm", lblLine1Btm);
            picSignLayout.Add(lblLine1Btm, 0, 38);
            Line1 = new Panel();
            Line1.Size = new Size(1, 1);
            RegisterControl("Line1", Line1);
            picSignLayout.Add(Line1, 0, 0);
            lblLine3Top = new Label();
            lblLine3Top.Size = new Size(185, 25);
            lblLine3Top.Text = "Line3";
            RegisterControl("lblLine3Top", lblLine3Top);
            picSignLayout.Add(lblLine3Top, 3, 67);
            lblLine2Top = new Label();
            lblLine2Top.Size = new Size(185, 25);
            lblLine2Top.Text = "Line2";
            RegisterControl("lblLine2Top", lblLine2Top);
            picSignLayout.Add(lblLine2Top, 3, 51);
            lblLine1Top = new Label();
            lblLine1Top.Size = new Size(185, 25);
            lblLine1Top.Text = "Line1";
            RegisterControl("lblLine1Top", lblLine1Top);
            picSignLayout.Add(lblLine1Top, 3, 35);
            lblexit = new Label();
            lblexit.Size = new Size(57, 17);
            lblexit.Text = "Exit";
            RegisterControl("lblexit", lblexit);
            picSignLayout.Add(lblexit, 64, 104);
            InitializeTool();
        }
    }
}