using Eto.Drawing;
using Eto.Forms;

namespace XtremeWorlds.Client.Tools
{
    public partial class frmSpellEditor : ToolForm
    {

        public readonly Label Label1;
        public readonly Label Label3;
        public readonly Label lblLevelReq;
        public readonly Label lblMP;
        public readonly Label Label7;
        public readonly TextBox txtName;
        public readonly GroupBox fraVitals;
        public readonly Label lblVitalMod;
        public readonly Label Label4;
        public readonly Slider scrlVitalMod;
        public readonly DropDown cmbType;
        public readonly GroupBox fraGiveItem;
        public readonly Label Label2;
        public readonly Label lblItemNum;
        public readonly Label Label5;
        public readonly Label lblItemValue;
        public readonly Slider scrlItemNum;
        public readonly Slider scrlItemValue;
        public readonly DropDown cmbClassReq;
        public readonly Slider scrlLevelReq;
        public readonly GroupBox fraMisc;
        public readonly Label lblAnim;
        public readonly Slider scrlAnim;
        public readonly SpritePreview picAnim;
        public readonly Slider scrlMP;
        public readonly GroupBox fraWarp;
        public readonly Label lblMapY;
        public readonly Label Label8;
        public readonly Label lblmapX;
        public readonly Label Label10;
        public readonly Label Label9;
        public readonly Slider scrlMapY;
        public readonly Slider scrlMapX;
        public readonly TextBox txtMap;
        public readonly Button cmdCancel;
        public readonly Button cmdOk;
        public readonly UITimer tmrSpellAnim;
        public readonly SpritePreview picSpells;
        public readonly Label lblDelivery;
        public readonly DropDown cmbDelivery;
        public readonly Label lblCastRange;
        public readonly TextBox txtCastRange;
        public readonly DropDown cmbArrow;

        public frmSpellEditor() : base("spell")
        {
            Title = "Spell Editor";
            ClientSize = new Size(332, 561);
            Resizable = false;
            var root = new PixelLayout();
            Content = root;
            Label1 = new Label();
            Label1.Size = new Size(49, 25);
            Label1.Text = "Name";
            RegisterControl("Label1", Label1);
            root.Add(Label1, 8, 8);
            Label3 = new Label();
            Label3.Size = new Size(49, 25);
            Label3.Text = "Level";
            RegisterControl("Label3", Label3);
            root.Add(Label3, 8, 88);
            lblLevelReq = new Label();
            lblLevelReq.Size = new Size(33, 25);
            lblLevelReq.Text = "1";
            RegisterControl("lblLevelReq", lblLevelReq);
            root.Add(lblLevelReq, 296, 88);
            lblMP = new Label();
            lblMP.Size = new Size(33, 25);
            lblMP.Text = "1";
            RegisterControl("lblMP", lblMP);
            root.Add(lblMP, 296, 120);
            Label7 = new Label();
            Label7.Size = new Size(49, 25);
            Label7.Text = "MP";
            RegisterControl("Label7", Label7);
            root.Add(Label7, 8, 120);
            txtName = new TextBox();
            txtName.Size = new Size(265, 26);
            RegisterControl("txtName", txtName);
            root.Add(txtName, 64, 8);
            fraVitals = new GroupBox();
            fraVitals.Size = new Size(321, 97);
            fraVitals.Text = "Vitals Data";
            fraVitals.Visible = false;
            RegisterControl("fraVitals", fraVitals);
            root.Add(fraVitals, 8, 200);
            var fraVitalsLayout = new PixelLayout();
            fraVitals.Content = fraVitalsLayout;
            lblVitalMod = new Label();
            lblVitalMod.Size = new Size(33, 25);
            lblVitalMod.Text = "1";
            RegisterControl("lblVitalMod", lblVitalMod);
            fraVitalsLayout.Add(lblVitalMod, 280, 8);
            Label4 = new Label();
            Label4.Size = new Size(73, 25);
            Label4.Text = "Vital Mod";
            RegisterControl("Label4", Label4);
            fraVitalsLayout.Add(Label4, 8, 8);
            scrlVitalMod = new Slider();
            scrlVitalMod.Size = new Size(193, 25);
            scrlVitalMod.MinValue = 0;
            scrlVitalMod.MaxValue = 255;
            scrlVitalMod.Value = 1;
            RegisterControl("scrlVitalMod", scrlVitalMod);
            fraVitalsLayout.Add(scrlVitalMod, 88, 8);
            cmbType = new DropDown();
            cmbType.Size = new Size(321, 26);
            cmbType.Items.Add("Add HP");
            cmbType.Items.Add("Add MP");
            cmbType.Items.Add("Add SP");
            cmbType.Items.Add("Sub HP");
            cmbType.Items.Add("Sub MP");
            cmbType.Items.Add("Sub SP");
            cmbType.Items.Add("Give Item");
            cmbType.Items.Add("Warp");
            cmbType.SelectedIndex = 0;
            RegisterControl("cmbType", cmbType);
            root.Add(cmbType, 8, 160);
            fraGiveItem = new GroupBox();
            fraGiveItem.Size = new Size(321, 97);
            fraGiveItem.Text = "Give Item";
            fraGiveItem.Visible = false;
            RegisterControl("fraGiveItem", fraGiveItem);
            root.Add(fraGiveItem, 8, 200);
            var fraGiveItemLayout = new PixelLayout();
            fraGiveItem.Content = fraGiveItemLayout;
            Label2 = new Label();
            Label2.Size = new Size(49, 25);
            Label2.Text = "Item";
            RegisterControl("Label2", Label2);
            fraGiveItemLayout.Add(Label2, 8, 8);
            lblItemNum = new Label();
            lblItemNum.Size = new Size(57, 25);
            lblItemNum.Text = "1";
            RegisterControl("lblItemNum", lblItemNum);
            fraGiveItemLayout.Add(lblItemNum, 256, 8);
            Label5 = new Label();
            Label5.Size = new Size(49, 25);
            Label5.Text = "Value";
            RegisterControl("Label5", Label5);
            fraGiveItemLayout.Add(Label5, 8, 40);
            lblItemValue = new Label();
            lblItemValue.Size = new Size(57, 25);
            lblItemValue.Text = "0";
            RegisterControl("lblItemValue", lblItemValue);
            fraGiveItemLayout.Add(lblItemValue, 256, 40);
            scrlItemNum = new Slider();
            scrlItemNum.Size = new Size(193, 25);
            scrlItemNum.MinValue = 1;
            scrlItemNum.MaxValue = 500;
            scrlItemNum.Value = 1;
            RegisterControl("scrlItemNum", scrlItemNum);
            fraGiveItemLayout.Add(scrlItemNum, 64, 8);
            scrlItemValue = new Slider();
            scrlItemValue.Size = new Size(193, 25);
            scrlItemValue.MinValue = 0;
            scrlItemValue.MaxValue = 32767;
            scrlItemValue.Value = 0;
            RegisterControl("scrlItemValue", scrlItemValue);
            fraGiveItemLayout.Add(scrlItemValue, 64, 40);
            cmbClassReq = new DropDown();
            cmbClassReq.Size = new Size(321, 26);
            RegisterControl("cmbClassReq", cmbClassReq);
            root.Add(cmbClassReq, 8, 48);
            scrlLevelReq = new Slider();
            scrlLevelReq.Size = new Size(233, 25);
            scrlLevelReq.MinValue = 1;
            scrlLevelReq.MaxValue = 255;
            scrlLevelReq.Value = 1;
            RegisterControl("scrlLevelReq", scrlLevelReq);
            root.Add(scrlLevelReq, 64, 88);
            fraMisc = new GroupBox();
            fraMisc.Size = new Size(321, 97);
            fraMisc.Text = "Animation";
            RegisterControl("fraMisc", fraMisc);
            root.Add(fraMisc, 8, 304);
            var fraMiscLayout = new PixelLayout();
            fraMisc.Content = fraMiscLayout;
            lblAnim = new Label();
            lblAnim.Size = new Size(33, 17);
            lblAnim.Text = "0";
            RegisterControl("lblAnim", lblAnim);
            fraMiscLayout.Add(lblAnim, 264, 8);
            scrlAnim = new Slider();
            scrlAnim.Size = new Size(241, 17);
            scrlAnim.MinValue = 0;
            scrlAnim.MaxValue = 100;
            scrlAnim.Value = 0;
            RegisterControl("scrlAnim", scrlAnim);
            fraMiscLayout.Add(scrlAnim, 8, 8);
            picAnim = new SpritePreview();
            picAnim.Size = new Size(33, 33);
            RegisterControl("picAnim", picAnim);
            fraMiscLayout.Add(picAnim, 16, 32);
            scrlMP = new Slider();
            scrlMP.Size = new Size(233, 25);
            scrlMP.MinValue = 1;
            scrlMP.MaxValue = 255;
            scrlMP.Value = 1;
            RegisterControl("scrlMP", scrlMP);
            root.Add(scrlMP, 64, 120);
            fraWarp = new GroupBox();
            fraWarp.Size = new Size(321, 97);
            fraWarp.Text = "Warp";
            fraWarp.Visible = false;
            RegisterControl("fraWarp", fraWarp);
            root.Add(fraWarp, 8, 200);
            var fraWarpLayout = new PixelLayout();
            fraWarp.Content = fraWarpLayout;
            lblMapY = new Label();
            lblMapY.Size = new Size(57, 25);
            lblMapY.Text = "1";
            RegisterControl("lblMapY", lblMapY);
            fraWarpLayout.Add(lblMapY, 256, 48);
            Label8 = new Label();
            Label8.Size = new Size(49, 25);
            Label8.Text = "Y";
            RegisterControl("Label8", Label8);
            fraWarpLayout.Add(Label8, 168, 48);
            lblmapX = new Label();
            lblmapX.Size = new Size(57, 25);
            lblmapX.Text = "1";
            RegisterControl("lblmapX", lblmapX);
            fraWarpLayout.Add(lblmapX, 96, 48);
            Label10 = new Label();
            Label10.Size = new Size(49, 25);
            Label10.Text = "X";
            RegisterControl("Label10", Label10);
            fraWarpLayout.Add(Label10, 8, 48);
            Label9 = new Label();
            Label9.Size = new Size(73, 25);
            Label9.Text = "Map";
            RegisterControl("Label9", Label9);
            fraWarpLayout.Add(Label9, 8, 8);
            scrlMapY = new Slider();
            scrlMapY.Size = new Size(89, 25);
            scrlMapY.MinValue = 0;
            scrlMapY.MaxValue = 11;
            scrlMapY.Value = 0;
            RegisterControl("scrlMapY", scrlMapY);
            fraWarpLayout.Add(scrlMapY, 192, 48);
            scrlMapX = new Slider();
            scrlMapX.Size = new Size(89, 25);
            scrlMapX.MinValue = 0;
            scrlMapX.MaxValue = 15;
            scrlMapX.Value = 0;
            RegisterControl("scrlMapX", scrlMapX);
            fraWarpLayout.Add(scrlMapX, 32, 48);
            txtMap = new TextBox();
            txtMap.Size = new Size(193, 26);
            RegisterControl("txtMap", txtMap);
            fraWarpLayout.Add(txtMap, 64, 8);
            cmdCancel = new Button();
            cmdCancel.Size = new Size(153, 33);
            cmdCancel.Text = "Cancel";
            RegisterControl("cmdCancel", cmdCancel);
            root.Add(cmdCancel, 172, 515);
            cmdOk = new Button();
            cmdOk.Size = new Size(153, 33);
            cmdOk.Text = "Ok";
            RegisterControl("cmdOk", cmdOk);
            root.Add(cmdOk, 13, 515);
            tmrSpellAnim = new UITimer();
            tmrSpellAnim.Interval = 0.050d;
            RegisterTimer(tmrSpellAnim);
            picSpells = new SpritePreview();
            picSpells.Size = new Size(89, 97);
            RegisterControl("picSpells", picSpells);
            root.Add(picSpells, 376, 8);
            lblDelivery = new Label();
            lblDelivery.Size = new Size(320, 20);
            lblDelivery.Text = "Spell delivery (all spell types)";
            RegisterControl("lblDelivery", lblDelivery);
            root.Add(lblDelivery, 8, 412);
            cmbDelivery = new DropDown();
            cmbDelivery.Size = new Size(320, 22);
            RegisterControl("cmbDelivery", cmbDelivery);
            root.Add(cmbDelivery, 8, 436);
            lblCastRange = new Label();
            lblCastRange.Size = new Size(178, 20);
            lblCastRange.Text = "Range cast: distance in tiles";
            RegisterControl("lblCastRange", lblCastRange);
            root.Add(lblCastRange, 8, 468);
            txtCastRange = new TextBox();
            txtCastRange.Size = new Size(90, 24);
            txtCastRange.Text = "32";
            RegisterControl("txtCastRange", txtCastRange);
            root.Add(txtCastRange, 238, 466);
            cmbArrow = new DropDown();
            cmbArrow.Size = new Size(178, 22);
            RegisterControl("cmbArrow", cmbArrow);
            root.Add(cmbArrow, 12, 489);
            InitializeTool();
        }
    }
}