<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>XtremeWorlds.Client.Engine</RootNamespace>
    <AssemblyName>XtremeWorlds.Client.Engine</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Network/NetworkState/NetworkState.csproj" />
    <ProjectReference Include="..\Core\Client.Common.csproj" />
    <PackageReference Include="FNA.NET" Version="2.2.11.2602" />
    <PackageReference Include="com.MirrorNetworking.Telepathy" Version="1.0.0" />
  </ItemGroup>
</Project>
